#!/usr/bin/env bash

run() {
  echo "$@"
  $@
}

cmd="./node_modules/prettier/bin/prettier.cjs --plugin ./dist/index.js --parser=lava-html --ignore-path=.prettierignore"

# run prettier with the built plugin
run $cmd "$@"
